[2024-01-20T11:15:11.739-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_python_operators.taskB manual__2024-01-20T19:15:04.434132+00:00 [queued]>
[2024-01-20T11:15:11.756-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_python_operators.taskB manual__2024-01-20T19:15:04.434132+00:00 [queued]>
[2024-01-20T11:15:11.757-0800] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-20T11:15:11.757-0800] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-01-20T11:15:11.757-0800] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-20T11:15:11.782-0800] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): taskB> on 2024-01-20 19:15:04.434132+00:00
[2024-01-20T11:15:11.784-0800] {standard_task_runner.py:55} INFO - Started process 2215 to run task
[2024-01-20T11:15:11.791-0800] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'execute_python_operators', 'taskB', 'manual__2024-01-20T19:15:04.434132+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/execute_python_operators.py', '--cfg-path', '/tmp/tmp3x66v14i']
[2024-01-20T11:15:11.800-0800] {standard_task_runner.py:83} INFO - Job 21: Subtask taskB
[2024-01-20T11:15:11.874-0800] {task_command.py:389} INFO - Running <TaskInstance: execute_python_operators.taskB manual__2024-01-20T19:15:04.434132+00:00 [running]> on host Mittu.
[2024-01-20T11:15:11.954-0800] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=madhu
AIRFLOW_CTX_DAG_ID=execute_python_operators
AIRFLOW_CTX_TASK_ID=taskB
AIRFLOW_CTX_EXECUTION_DATE=2024-01-20T19:15:04.434132+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-20T19:15:04.434132+00:00
[2024-01-20T11:15:11.955-0800] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mirukulla/airflow/dags/execute_python_operators.py", line 16, in task_b
    time.sleep(5)
NameError: name 'time' is not defined
[2024-01-20T11:15:11.959-0800] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=execute_python_operators, task_id=taskB, execution_date=20240120T191504, start_date=20240120T191511, end_date=20240120T191511
[2024-01-20T11:15:11.997-0800] {standard_task_runner.py:100} ERROR - Failed to execute job 21 for task taskB (name 'time' is not defined; 2215)
[2024-01-20T11:15:12.004-0800] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-01-20T11:15:12.050-0800] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
