[2024-01-20T11:13:33.830-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_python_operators.taskB manual__2024-01-20T19:13:29.968427+00:00 [queued]>
[2024-01-20T11:13:33.838-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_python_operators.taskB manual__2024-01-20T19:13:29.968427+00:00 [queued]>
[2024-01-20T11:13:33.838-0800] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-20T11:13:33.839-0800] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-01-20T11:13:33.839-0800] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-20T11:13:33.859-0800] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): taskB> on 2024-01-20 19:13:29.968427+00:00
[2024-01-20T11:13:33.861-0800] {standard_task_runner.py:55} INFO - Started process 2055 to run task
[2024-01-20T11:13:33.863-0800] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'execute_python_operators', 'taskB', 'manual__2024-01-20T19:13:29.968427+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/execute_python_operators.py', '--cfg-path', '/tmp/tmpjx7bhd5u']
[2024-01-20T11:13:33.864-0800] {standard_task_runner.py:83} INFO - Job 18: Subtask taskB
[2024-01-20T11:13:33.910-0800] {task_command.py:389} INFO - Running <TaskInstance: execute_python_operators.taskB manual__2024-01-20T19:13:29.968427+00:00 [running]> on host Mittu.
[2024-01-20T11:13:33.968-0800] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=madhu
AIRFLOW_CTX_DAG_ID=execute_python_operators
AIRFLOW_CTX_TASK_ID=taskB
AIRFLOW_CTX_EXECUTION_DATE=2024-01-20T19:13:29.968427+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-20T19:13:29.968427+00:00
[2024-01-20T11:13:33.969-0800] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mirukulla/airflow/dags/execute_python_operators.py", line 16, in task_b
    time.sleep(5)
NameError: name 'time' is not defined
[2024-01-20T11:13:33.974-0800] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=execute_python_operators, task_id=taskB, execution_date=20240120T191329, start_date=20240120T191333, end_date=20240120T191333
[2024-01-20T11:13:33.991-0800] {standard_task_runner.py:100} ERROR - Failed to execute job 18 for task taskB (name 'time' is not defined; 2055)
[2024-01-20T11:13:33.996-0800] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-01-20T11:13:34.009-0800] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
