[2024-01-21T11:52:31.772-0800] {processor.py:153} INFO - Started process (PID=32430) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:52:31.774-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T11:52:31.776-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:52:31.776-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:52:31.800-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:52:31.929-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:52:31.928-0800] {manager.py:504} INFO - Created Permission View: can read on DAG:cron_catchup_backfill
[2024-01-21T11:52:31.949-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:52:31.948-0800] {manager.py:504} INFO - Created Permission View: can edit on DAG:cron_catchup_backfill
[2024-01-21T11:52:31.965-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:52:31.965-0800] {manager.py:504} INFO - Created Permission View: can delete on DAG:cron_catchup_backfill
[2024-01-21T11:52:31.966-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:52:31.965-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T11:52:31.979-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:52:31.979-0800] {dag.py:2726} INFO - Creating ORM DAG for cron_catchup_backfill
[2024-01-21T11:52:31.989-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:52:31.989-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2024-01-16T00:00:00+00:00, run_after=2024-01-17T00:00:00+00:00
[2024-01-21T11:52:32.026-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.257 seconds
[2024-01-21T11:53:02.551-0800] {processor.py:153} INFO - Started process (PID=32481) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:53:02.552-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T11:53:02.553-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:53:02.553-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:53:02.573-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:53:02.590-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:53:02.590-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T11:53:02.607-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:53:02.607-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2024-01-16T00:00:00+00:00, run_after=2024-01-17T00:00:00+00:00
[2024-01-21T11:53:02.638-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.092 seconds
[2024-01-21T11:53:33.330-0800] {processor.py:153} INFO - Started process (PID=32535) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:53:33.332-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T11:53:33.332-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:53:33.332-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:53:33.368-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:53:33.398-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:53:33.398-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T11:53:33.416-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:53:33.416-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2024-01-16T00:00:00+00:00, run_after=2024-01-17T00:00:00+00:00
[2024-01-21T11:53:33.443-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.118 seconds
[2024-01-21T11:54:04.105-0800] {processor.py:153} INFO - Started process (PID=32589) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:54:04.141-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T11:54:04.142-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:54:04.142-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:54:04.185-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:54:04.216-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:54:04.216-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T11:54:04.254-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:54:04.254-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2024-01-16T00:00:00+00:00, run_after=2024-01-17T00:00:00+00:00
[2024-01-21T11:54:04.365-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.263 seconds
[2024-01-21T11:54:34.689-0800] {processor.py:153} INFO - Started process (PID=32643) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:54:34.691-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T11:54:34.692-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:54:34.692-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:54:34.716-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:54:34.742-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:54:34.741-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T11:54:34.780-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:54:34.779-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2024-01-16T00:00:00+00:00, run_after=2024-01-17T00:00:00+00:00
[2024-01-21T11:54:34.815-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.131 seconds
[2024-01-21T11:55:05.105-0800] {processor.py:153} INFO - Started process (PID=32694) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:55:05.133-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T11:55:05.133-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:55:05.133-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:55:05.153-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:55:05.169-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:55:05.169-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T11:55:05.187-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:55:05.187-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2024-01-16T00:00:00+00:00, run_after=2024-01-17T00:00:00+00:00
[2024-01-21T11:55:05.218-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.117 seconds
[2024-01-21T11:55:35.798-0800] {processor.py:153} INFO - Started process (PID=32748) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:55:35.799-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T11:55:35.800-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:55:35.800-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:55:35.820-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:55:35.838-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:55:35.837-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T11:55:35.858-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:55:35.858-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2024-01-16T00:00:00+00:00, run_after=2024-01-17T00:00:00+00:00
[2024-01-21T11:55:35.890-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.095 seconds
[2024-01-21T11:56:11.213-0800] {processor.py:153} INFO - Started process (PID=491) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:56:11.215-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T11:56:11.215-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:56:11.215-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:56:11.236-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:56:11.258-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:56:11.257-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T11:56:11.282-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:56:11.282-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2024-01-19T00:00:00+00:00, run_after=2024-01-20T00:00:00+00:00
[2024-01-21T11:56:11.312-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.103 seconds
[2024-01-21T11:56:45.733-0800] {processor.py:153} INFO - Started process (PID=638) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:56:45.761-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T11:56:45.762-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:56:45.762-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:56:45.787-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:56:45.809-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:56:45.809-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T11:56:45.834-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:56:45.834-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2024-01-20T00:00:00+00:00, run_after=2024-01-21T00:00:00+00:00
[2024-01-21T11:56:45.862-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.133 seconds
[2024-01-21T11:57:16.658-0800] {processor.py:153} INFO - Started process (PID=720) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:57:16.665-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T11:57:16.666-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:57:16.666-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:57:16.687-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:57:16.707-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:57:16.706-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T11:57:16.728-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:57:16.728-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2024-01-21T00:00:00+00:00, run_after=2024-01-22T00:00:00+00:00
[2024-01-21T11:57:16.760-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.105 seconds
[2024-01-21T11:57:47.835-0800] {processor.py:153} INFO - Started process (PID=774) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:57:47.837-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T11:57:47.838-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:57:47.838-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:57:47.863-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:57:47.885-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:57:47.885-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T11:57:47.911-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:57:47.911-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2024-01-21T00:00:00+00:00, run_after=2024-01-22T00:00:00+00:00
[2024-01-21T11:57:47.950-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.118 seconds
[2024-01-21T11:58:18.512-0800] {processor.py:153} INFO - Started process (PID=825) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:58:18.555-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T11:58:18.556-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:58:18.556-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:58:18.591-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:58:18.661-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:58:18.660-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T11:58:18.670-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:58:18.669-0800] {dag.py:2726} INFO - Creating ORM DAG for cron_catchup_backfill
[2024-01-21T11:58:18.678-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:58:18.677-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2024-01-16T00:00:00+00:00, run_after=2024-01-17T00:00:00+00:00
[2024-01-21T11:58:18.724-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.215 seconds
[2024-01-21T11:58:49.040-0800] {processor.py:153} INFO - Started process (PID=879) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:58:49.083-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T11:58:49.085-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:58:49.084-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:58:49.113-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:58:49.131-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:58:49.130-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T11:58:49.149-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:58:49.149-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2024-01-16T00:00:00+00:00, run_after=2024-01-17T00:00:00+00:00
[2024-01-21T11:58:49.175-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.140 seconds
[2024-01-21T11:59:19.489-0800] {processor.py:153} INFO - Started process (PID=933) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:59:19.492-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T11:59:19.493-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:59:19.493-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:59:19.515-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:59:19.532-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:59:19.532-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T11:59:19.548-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:59:19.548-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2024-01-16T00:00:00+00:00, run_after=2024-01-17T00:00:00+00:00
[2024-01-21T11:59:19.589-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.104 seconds
[2024-01-21T11:59:50.122-0800] {processor.py:153} INFO - Started process (PID=984) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:59:50.159-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T11:59:50.160-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:59:50.160-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:59:50.186-0800] {logging_mixin.py:137} INFO - [2024-01-21T11:59:50.178-0800] {dagbag.py:438} ERROR - Failed to bag_dag: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 172, in _alphaconv
    return cls.ALPHACONV[index][key]
KeyError: '0*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/timetables/_cron.py", line 88, in validate
    croniter(self._expression)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 778, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 685, in _expand
    low = "{0}".format(cls._alphaconv(i, low, expressions))
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 174, in _alphaconv
    raise CroniterNotAlphaError(
croniter.croniter.CroniterNotAlphaError: [0 0*/12 * * 6, 0] is not acceptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 435, in _process_modules
    dag.validate()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 669, in validate
    self.timetable.validate()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/timetables/_cron.py", line 90, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: [0 0*/12 * * 6, 0] is not acceptable
[2024-01-21T11:59:50.186-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T11:59:50.208-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.091 seconds
[2024-01-21T12:00:20.721-0800] {processor.py:153} INFO - Started process (PID=1038) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:00:20.772-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:00:20.773-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:00:20.773-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:00:20.799-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:00:20.797-0800] {dagbag.py:438} ERROR - Failed to bag_dag: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 172, in _alphaconv
    return cls.ALPHACONV[index][key]
KeyError: '0*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/timetables/_cron.py", line 88, in validate
    croniter(self._expression)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 778, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 685, in _expand
    low = "{0}".format(cls._alphaconv(i, low, expressions))
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 174, in _alphaconv
    raise CroniterNotAlphaError(
croniter.croniter.CroniterNotAlphaError: [0 0*/12 * * 6, 0] is not acceptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 435, in _process_modules
    dag.validate()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 669, in validate
    self.timetable.validate()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/timetables/_cron.py", line 90, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: [0 0*/12 * * 6, 0] is not acceptable
[2024-01-21T12:00:20.800-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:00:20.828-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.111 seconds
[2024-01-21T12:00:51.221-0800] {processor.py:153} INFO - Started process (PID=1092) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:00:51.224-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:00:51.225-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:00:51.225-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:00:51.242-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:00:51.241-0800] {dagbag.py:438} ERROR - Failed to bag_dag: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 172, in _alphaconv
    return cls.ALPHACONV[index][key]
KeyError: '0*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/timetables/_cron.py", line 88, in validate
    croniter(self._expression)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 778, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 685, in _expand
    low = "{0}".format(cls._alphaconv(i, low, expressions))
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 174, in _alphaconv
    raise CroniterNotAlphaError(
croniter.croniter.CroniterNotAlphaError: [0 0*/12 * * 6, 0] is not acceptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 435, in _process_modules
    dag.validate()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 669, in validate
    self.timetable.validate()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/timetables/_cron.py", line 90, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: [0 0*/12 * * 6, 0] is not acceptable
[2024-01-21T12:00:51.242-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:00:51.271-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.057 seconds
[2024-01-21T12:01:21.701-0800] {processor.py:153} INFO - Started process (PID=1146) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:01:21.732-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:01:21.733-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:01:21.733-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:01:21.749-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:01:21.747-0800] {dagbag.py:438} ERROR - Failed to bag_dag: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 172, in _alphaconv
    return cls.ALPHACONV[index][key]
KeyError: '0*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/timetables/_cron.py", line 88, in validate
    croniter(self._expression)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 778, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 685, in _expand
    low = "{0}".format(cls._alphaconv(i, low, expressions))
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 174, in _alphaconv
    raise CroniterNotAlphaError(
croniter.croniter.CroniterNotAlphaError: [0 0*/12 * * 6, 0] is not acceptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 435, in _process_modules
    dag.validate()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 669, in validate
    self.timetable.validate()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/timetables/_cron.py", line 90, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: [0 0*/12 * * 6, 0] is not acceptable
[2024-01-21T12:01:21.749-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:01:21.772-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.075 seconds
[2024-01-21T12:01:52.045-0800] {processor.py:153} INFO - Started process (PID=1197) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:01:52.092-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:01:52.094-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:01:52.094-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:01:52.121-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:01:52.120-0800] {dagbag.py:438} ERROR - Failed to bag_dag: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 172, in _alphaconv
    return cls.ALPHACONV[index][key]
KeyError: '0*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/timetables/_cron.py", line 88, in validate
    croniter(self._expression)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 778, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 685, in _expand
    low = "{0}".format(cls._alphaconv(i, low, expressions))
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 174, in _alphaconv
    raise CroniterNotAlphaError(
croniter.croniter.CroniterNotAlphaError: [0 0*/12 * * 6, 0] is not acceptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 435, in _process_modules
    dag.validate()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 669, in validate
    self.timetable.validate()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/timetables/_cron.py", line 90, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: [0 0*/12 * * 6, 0] is not acceptable
[2024-01-21T12:01:52.122-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:01:52.157-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.116 seconds
[2024-01-21T12:02:22.594-0800] {processor.py:153} INFO - Started process (PID=1251) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:02:22.596-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:02:22.597-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:02:22.597-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:02:22.614-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:02:22.613-0800] {dagbag.py:438} ERROR - Failed to bag_dag: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 172, in _alphaconv
    return cls.ALPHACONV[index][key]
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/timetables/_cron.py", line 88, in validate
    croniter(self._expression)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 778, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 721, in _expand
    t = cls._alphaconv(i, t, expressions)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 174, in _alphaconv
    raise CroniterNotAlphaError(
croniter.croniter.CroniterNotAlphaError: [0 */12 * * 6, 0] is not acceptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 435, in _process_modules
    dag.validate()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 669, in validate
    self.timetable.validate()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/timetables/_cron.py", line 90, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: [0 */12 * * 6, 0] is not acceptable
[2024-01-21T12:02:22.615-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:02:22.641-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.050 seconds
[2024-01-21T12:02:53.056-0800] {processor.py:153} INFO - Started process (PID=1305) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:02:53.086-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:02:53.086-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:02:53.086-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:02:53.102-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:02:53.101-0800] {dagbag.py:438} ERROR - Failed to bag_dag: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 172, in _alphaconv
    return cls.ALPHACONV[index][key]
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/timetables/_cron.py", line 88, in validate
    croniter(self._expression)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 778, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 721, in _expand
    t = cls._alphaconv(i, t, expressions)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/croniter/croniter.py", line 174, in _alphaconv
    raise CroniterNotAlphaError(
croniter.croniter.CroniterNotAlphaError: [0 */12 * * 6, 0] is not acceptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 435, in _process_modules
    dag.validate()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 669, in validate
    self.timetable.validate()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/timetables/_cron.py", line 90, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: [0 */12 * * 6, 0] is not acceptable
[2024-01-21T12:02:53.102-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:02:53.125-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.071 seconds
[2024-01-21T12:03:24.001-0800] {processor.py:153} INFO - Started process (PID=1359) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:03:24.002-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:03:24.003-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:03:24.003-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:03:24.049-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:03:24.110-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:03:24.109-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T12:03:24.130-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:03:24.130-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2023-12-23T00:00:00+00:00, run_after=2023-12-23T12:00:00+00:00
[2024-01-21T12:03:24.242-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.244 seconds
[2024-01-21T12:03:56.858-0800] {processor.py:153} INFO - Started process (PID=1432) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:03:56.861-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:03:56.862-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:03:56.862-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:03:56.889-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:03:56.914-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:03:56.914-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T12:03:56.942-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:03:56.942-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2023-12-23T12:00:00+00:00, run_after=2023-12-30T00:00:00+00:00
[2024-01-21T12:03:56.992-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.140 seconds
[2024-01-21T12:04:54.630-0800] {processor.py:153} INFO - Started process (PID=1629) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:04:54.669-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:04:54.670-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:04:54.670-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:04:54.693-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:04:54.736-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:04:54.736-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T12:04:54.744-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:04:54.744-0800] {dag.py:2726} INFO - Creating ORM DAG for cron_catchup_backfill
[2024-01-21T12:04:54.758-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:04:54.758-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2023-12-23T00:00:00+00:00, run_after=2023-12-23T12:00:00+00:00
[2024-01-21T12:04:54.790-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.163 seconds
[2024-01-21T12:05:25.549-0800] {processor.py:153} INFO - Started process (PID=1680) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:05:25.590-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:05:25.592-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:05:25.592-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:05:25.615-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:05:25.635-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:05:25.635-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T12:05:25.653-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:05:25.653-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2023-12-23T00:00:00+00:00, run_after=2023-12-23T12:00:00+00:00
[2024-01-21T12:05:25.681-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.136 seconds
[2024-01-21T12:05:56.189-0800] {processor.py:153} INFO - Started process (PID=1734) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:05:56.233-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:05:56.234-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:05:56.234-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:05:56.253-0800] {processor.py:753} INFO - DAG(s) dict_keys(['cron_catchup_backfill']) retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:05:56.281-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:05:56.281-0800] {dag.py:2705} INFO - Sync 1 DAGs
[2024-01-21T12:05:56.299-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:05:56.299-0800] {dag.py:3452} INFO - Setting next_dagrun for cron_catchup_backfill to 2023-12-23T00:00:00+00:00, run_after=2023-12-23T12:00:00+00:00
[2024-01-21T12:05:56.328-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.143 seconds
[2024-01-21T12:06:27.132-0800] {processor.py:153} INFO - Started process (PID=1788) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:06:27.134-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:06:27.135-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:06:27.135-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:06:27.141-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:06:27.139-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:06:27.142-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:06:27.174-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.047 seconds
[2024-01-21T12:06:57.651-0800] {processor.py:153} INFO - Started process (PID=1842) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:06:57.687-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:06:57.688-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:06:57.688-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:06:57.692-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:06:57.691-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:06:57.693-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:06:57.728-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.080 seconds
[2024-01-21T12:07:28.477-0800] {processor.py:153} INFO - Started process (PID=1893) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:07:28.502-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:07:28.503-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:07:28.503-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:07:28.508-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:07:28.507-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:07:28.509-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:07:28.541-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.068 seconds
[2024-01-21T12:07:59.083-0800] {processor.py:153} INFO - Started process (PID=1947) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:07:59.086-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:07:59.087-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:07:59.087-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:07:59.098-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:07:59.097-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:07:59.099-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:07:59.137-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.058 seconds
[2024-01-21T12:08:29.648-0800] {processor.py:153} INFO - Started process (PID=2001) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:08:29.649-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:08:29.649-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:08:29.649-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:08:29.652-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:08:29.651-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:08:29.652-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:08:29.698-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.054 seconds
[2024-01-21T12:09:00.351-0800] {processor.py:153} INFO - Started process (PID=2055) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:09:00.353-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:09:00.353-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:09:00.353-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:09:00.356-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:09:00.355-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:09:00.356-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:09:00.381-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.032 seconds
[2024-01-21T12:09:31.208-0800] {processor.py:153} INFO - Started process (PID=2106) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:09:31.211-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:09:31.213-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:09:31.213-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:09:31.216-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:09:31.216-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:09:31.217-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:09:31.247-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.045 seconds
[2024-01-21T12:10:01.665-0800] {processor.py:153} INFO - Started process (PID=2160) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:10:01.701-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:10:01.702-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:10:01.702-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:10:01.706-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:10:01.705-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:10:01.706-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:10:01.734-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.072 seconds
[2024-01-21T12:10:32.322-0800] {processor.py:153} INFO - Started process (PID=2211) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:10:32.325-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:10:32.326-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:10:32.326-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:10:32.330-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:10:32.329-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:10:32.330-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:10:32.355-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.037 seconds
[2024-01-21T12:11:03.224-0800] {processor.py:153} INFO - Started process (PID=2265) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:11:03.226-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:11:03.227-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:11:03.226-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:11:03.231-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:11:03.229-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:11:03.231-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:11:03.262-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.043 seconds
[2024-01-21T12:11:34.152-0800] {processor.py:153} INFO - Started process (PID=2319) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:11:34.183-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:11:34.184-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:11:34.184-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:11:34.187-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:11:34.186-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:11:34.187-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:11:34.220-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.071 seconds
[2024-01-21T12:12:04.918-0800] {processor.py:153} INFO - Started process (PID=2370) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:12:04.919-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:12:04.921-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:12:04.920-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:12:04.924-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:12:04.923-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:12:04.925-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:12:04.952-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.038 seconds
[2024-01-21T12:12:35.694-0800] {processor.py:153} INFO - Started process (PID=2424) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:12:35.734-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:12:35.735-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:12:35.734-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:12:35.739-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:12:35.738-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:12:35.739-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:12:35.771-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.081 seconds
[2024-01-21T12:13:06.741-0800] {processor.py:153} INFO - Started process (PID=2478) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:13:06.787-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:13:06.788-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:13:06.788-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:13:06.793-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:13:06.792-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:13:06.793-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:13:06.834-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.100 seconds
[2024-01-21T12:13:37.242-0800] {processor.py:153} INFO - Started process (PID=2529) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:13:37.275-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:13:37.276-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:13:37.276-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:13:37.281-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:13:37.280-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:13:37.281-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:13:37.319-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.083 seconds
[2024-01-21T12:14:07.764-0800] {processor.py:153} INFO - Started process (PID=2583) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:14:07.767-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:14:07.768-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:14:07.767-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:14:07.771-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:14:07.770-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:14:07.771-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:14:07.798-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.038 seconds
[2024-01-21T12:14:38.423-0800] {processor.py:153} INFO - Started process (PID=2638) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:14:38.425-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:14:38.426-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:14:38.425-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:14:38.428-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:14:38.428-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:14:38.428-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:14:38.454-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.035 seconds
[2024-01-21T12:15:08.592-0800] {processor.py:153} INFO - Started process (PID=2787) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:15:08.622-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:15:08.623-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:15:08.623-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:15:08.625-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:15:08.625-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:15:08.625-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:15:08.657-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.067 seconds
[2024-01-21T12:15:38.761-0800] {processor.py:153} INFO - Started process (PID=2841) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:15:38.789-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:15:38.790-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:15:38.790-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:15:38.793-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:15:38.792-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:15:38.794-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:15:38.820-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.061 seconds
[2024-01-21T12:16:08.973-0800] {processor.py:153} INFO - Started process (PID=2892) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:16:08.975-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:16:08.975-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:16:08.975-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:16:08.978-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:16:08.977-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:16:08.978-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:16:09.003-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.033 seconds
[2024-01-21T12:16:39.528-0800] {processor.py:153} INFO - Started process (PID=2946) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:16:39.562-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:16:39.563-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:16:39.563-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:16:39.567-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:16:39.566-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:16:39.568-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:16:39.595-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.072 seconds
[2024-01-21T12:17:10.179-0800] {processor.py:153} INFO - Started process (PID=3000) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:17:10.182-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:17:10.183-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:17:10.183-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:17:10.186-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:17:10.185-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:17:10.186-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:17:10.213-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.038 seconds
[2024-01-21T12:17:41.974-0800] {processor.py:153} INFO - Started process (PID=3055) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:17:41.976-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:17:41.977-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:17:41.977-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:17:41.980-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:17:41.979-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:17:41.981-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:17:42.005-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.035 seconds
[2024-01-21T12:18:12.721-0800] {processor.py:153} INFO - Started process (PID=3109) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:18:12.723-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:18:12.724-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:18:12.724-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:18:12.726-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:18:12.726-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:18:12.726-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:18:12.749-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.031 seconds
[2024-01-21T12:18:43.386-0800] {processor.py:153} INFO - Started process (PID=3163) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:18:43.419-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:18:43.420-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:18:43.420-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:18:43.425-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:18:43.424-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:18:43.425-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:18:43.468-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.087 seconds
[2024-01-21T12:19:13.808-0800] {processor.py:153} INFO - Started process (PID=3217) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:19:13.809-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:19:13.810-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:19:13.810-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:19:13.812-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:19:13.812-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:19:13.813-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:19:13.841-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.035 seconds
[2024-01-21T12:19:44.351-0800] {processor.py:153} INFO - Started process (PID=3268) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:19:44.352-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:19:44.353-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:19:44.353-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:19:44.357-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:19:44.357-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:19:44.358-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:19:44.384-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.038 seconds
[2024-01-21T12:20:14.915-0800] {processor.py:153} INFO - Started process (PID=3322) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:20:14.939-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:20:14.940-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:20:14.940-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:20:14.943-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:20:14.942-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:20:14.943-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:20:14.967-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.057 seconds
[2024-01-21T12:20:45.494-0800] {processor.py:153} INFO - Started process (PID=3376) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:20:45.536-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:20:45.537-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:20:45.537-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:20:45.540-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:20:45.539-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:20:45.540-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:20:45.567-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.076 seconds
[2024-01-21T12:21:16.148-0800] {processor.py:153} INFO - Started process (PID=3430) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:21:16.181-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:21:16.183-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:21:16.182-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:21:16.187-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:21:16.186-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:21:16.187-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:21:16.218-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.076 seconds
[2024-01-21T12:21:46.835-0800] {processor.py:153} INFO - Started process (PID=3484) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:21:46.857-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:21:46.858-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:21:46.858-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:21:46.861-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:21:46.860-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:21:46.861-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:21:46.884-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.052 seconds
[2024-01-21T12:22:17.544-0800] {processor.py:153} INFO - Started process (PID=3538) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:22:17.580-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:22:17.581-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:22:17.580-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:22:17.583-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:22:17.583-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:22:17.584-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:22:17.607-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.066 seconds
[2024-01-21T12:22:49.597-0800] {processor.py:153} INFO - Started process (PID=3592) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:22:49.630-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:22:49.633-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:22:49.632-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:22:49.646-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:22:49.644-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:22:49.647-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:22:49.691-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.099 seconds
[2024-01-21T12:23:20.044-0800] {processor.py:153} INFO - Started process (PID=3646) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:23:20.082-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:23:20.083-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:23:20.083-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:23:20.087-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:23:20.086-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:23:20.088-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:23:20.121-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.080 seconds
[2024-01-21T12:23:50.885-0800] {processor.py:153} INFO - Started process (PID=3700) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:23:50.888-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:23:50.889-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:23:50.888-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:23:50.892-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:23:50.891-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:23:50.892-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:23:50.922-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.040 seconds
[2024-01-21T12:24:21.331-0800] {processor.py:153} INFO - Started process (PID=3751) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:24:21.378-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:24:21.378-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:24:21.378-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:24:21.380-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:24:21.380-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:24:21.381-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:24:21.402-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.074 seconds
[2024-01-21T12:24:52.192-0800] {processor.py:153} INFO - Started process (PID=3805) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:24:52.221-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:24:52.223-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:24:52.222-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:24:52.227-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:24:52.225-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:24:52.228-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:24:52.253-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.068 seconds
[2024-01-21T12:25:23.388-0800] {processor.py:153} INFO - Started process (PID=3859) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:25:23.390-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:25:23.391-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:25:23.391-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:25:23.395-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:25:23.394-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:25:23.395-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:25:23.422-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.039 seconds
[2024-01-21T12:25:53.904-0800] {processor.py:153} INFO - Started process (PID=3913) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:25:53.915-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:25:53.916-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:25:53.916-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:25:53.920-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:25:53.918-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:25:53.920-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:25:53.949-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.051 seconds
[2024-01-21T12:26:24.451-0800] {processor.py:153} INFO - Started process (PID=4229) to work on /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:26:24.481-0800] {processor.py:743} INFO - Processing file /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py for tasks to queue
[2024-01-21T12:26:24.481-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:26:24.481-0800] {dagbag.py:532} INFO - Filling up the DagBag from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:26:24.483-0800] {logging_mixin.py:137} INFO - [2024-01-21T12:26:24.483-0800] {dagbag.py:341} ERROR - Failed to import: /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py", line 124
    -------------------------------------------------------------
                                                                 ^
SyntaxError: invalid syntax
[2024-01-21T12:26:24.484-0800] {processor.py:755} WARNING - No viable dags retrieved from /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py
[2024-01-21T12:26:24.507-0800] {processor.py:175} INFO - Processing /home/mirukulla/airflow/dags/executing_cron_catchup_backfill.py took 0.061 seconds
